# Generated by Django 5.1.7 on 2025-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_new',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
