# Generated by Django 5.1.7 on 2025-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_duration_new_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
