# Generated by Django 5.1.7 on 2025-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_new',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
    ]
